apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-india
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:alpine # Lightweight for Indian bandwidth
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: TZ
          value: Asia/Kolkata # Indian timezone
